site_name: Remark Admin Template Docs
repo_url: https://github.com/amazingSurge/remark-docs/
site_author: amazingsurge
pages:
- [index.md, Home]
- [overview.md, 1. Overview]
- [build.md, 2. Building Tools]
- [files.md, 3. File Structure]
- [global.md, 4. Global Assets]
- [style.md, 5. Customize Styles]
- [javascript.md, 6. Modular JavaScript]
- [structure.md, 7. Template Structure]
- [components.md, 8. Components]
- [psd.md, 9. PSD Files]
- [credits.md, 10. Sources and Credits]
- [support.md, 11. Support]
- [changelog.md, 12. Changelog]
theme: readthedocs
use_directory_urls: false
