site_name: Remark Admin Template Docs
repo_url: https://github.com/amazingSurge/remark-docs/
site_author: amazingsurge
pages:
- [index.md, Home]
- [overview.md, 1. Overview]
- [generator.md, 2. Generator]
- [build.md, 3. Building Tools]
- [files.md, 4. File Structure]
- [global.md, 5. Global Assets]
- [style.md, 6. Customize Styles]
- [javascript.md, 7. Modular JavaScript]
- [structure.md, 8. Template Structure]
- [components.md, 9. Components]
- [psd.md, 10. PSD Files]
- [credits.md, 11. Sources and Credits]
- [support.md, 12. Support]
- [changelog.md, 13. Changelog]
- [migration.md, 14. Migration]
theme: readthedocs
use_directory_urls: false
